name: YaizuComLib CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      run: |
        cd build
        ./build.sh
    - name: exec pwd ls
      run: |
        pwd
        ls -l
